// Hand-drawn 16x16 pixel icons for jasp.os. One char per pixel:
//   . transparent   # ink   w paper   g platinum   s shade
//   v violet        l lavender        y sticky     k mustard   r tomato
//   h hair          f skin            F skin shade t tee       b blue
// Rendered as SVG rects (crisp edges), colours come from CSS custom properties,
// so 1-bit mode can recolour everything without redrawing.

const BITMAPS = {
  doc: [
    "................",
    "...########.....",
    "...#wwwwww##....",
    "...#wwwwww#w#...",
    "...#wwwwww####..",
    "...#wwwwwwwww#..",
    "...#w#####www#..",
    "...#wwwwwwwww#..",
    "...#w######ww#..",
    "...#wwwwwwwww#..",
    "...#w####wwww#..",
    "...#wwwwwwwww#..",
    "...#w######ww#..",
    "...#wwwwwwwww#..",
    "...###########..",
    "................",
  ],
  folder: [
    "................",
    "................",
    ".####...........",
    "#llll#..........",
    "#lllll#########.",
    "#wwwwwwwwwwwww#.",
    "#lllllllllllll#.",
    "#lllllllllllll#.",
    "#lllllllllllll#.",
    "#lllllllllllll#.",
    "#lllllllllllll#.",
    "#lllllllllllll#.",
    "#vvvvvvvvvvvvv#.",
    "###############.",
    "................",
    "................",
  ],
  folder2: [
    "................",
    "................",
    ".####...........",
    "#yyyy#..........",
    "#yyyyy#########.",
    "#wwwwwwwwwwwww#.",
    "#yyyyyyyyyyyyy#.",
    "#yyyyyyvyyyyyy#.",
    "#yyyyyvvvyyyyy#.",
    "#yyyyyyvyyyyyy#.",
    "#yyyyyyyyyyyyy#.",
    "#yyyyyyyyyyyyy#.",
    "#kkkkkkkkkkkkk#.",
    "###############.",
    "................",
    "................",
  ],
  log: [
    "................",
    "..############..",
    "..#vvvvvvvvvv#..",
    "..############..",
    "..#yyyyyyyyyy#..",
    "..#y##y####yy#..",
    "..#yyyyyyyyyy#..",
    "..#y#y######y#..",
    "..#yyyyyyyyyy#..",
    "..#y##y###yyy#..",
    "..#yyyyyyyyyy#..",
    "..#y#y####yyy#..",
    "..#yyyyyyyyyy#..",
    "..############..",
    "................",
    "................",
  ],
  work: [
    "................",
    "................",
    "......####......",
    ".....#....#.....",
    "..############..",
    ".#gggggggggggg#.",
    ".#gggggggggggg#.",
    ".#gggggggggggg#.",
    ".######vv######.",
    ".#ggggg##ggggg#.",
    ".#gggggggggggg#.",
    ".#gggggggggggg#.",
    ".#ssssssssssss#.",
    "..############..",
    "................",
    "................",
  ],
  mail: [
    "................",
    "................",
    "................",
    ".##############.",
    ".##wwwwwwwwww##.",
    ".#w##wwwwww##w#.",
    ".#www##ww##www#.",
    ".#wwwww##wwwww#.",
    ".#wwwwwwwwwwww#.",
    ".#wwwwwwwwwvvw#.",
    ".#wwwwwwwwwvvw#.",
    ".#wwwwwwwwwwww#.",
    ".##############.",
    "................",
    "................",
    "................",
  ],
  trash: [
    "................",
    "......####......",
    "..############..",
    "..#gggggggggg#..",
    "..############..",
    "...#gg#gg#gg#...",
    "...#gg#gg#gg#...",
    "...#gg#gg#gg#...",
    "...#gg#gg#gg#...",
    "...#gg#gg#gg#...",
    "...#gg#gg#gg#...",
    "...#gg#gg#gg#...",
    "...#ss#ss#ss#...",
    "...##########...",
    "................",
    "................",
  ],
  suitcase: [
    "................",
    "......####......",
    "......#..#......",
    "...##########...",
    "...#vvvvvvvv#...",
    "...#v#vvvv#v#...",
    "...#v#vyyv#v#...",
    "...#v#vyyv#v#...",
    "...#v#vvvv#v#...",
    "...#v#vvvv#v#...",
    "...#v#vvvv#v#...",
    "...#vvvvvvvv#...",
    "...##########...",
    "....#......#....",
    "................",
    "................",
  ],
  pizza: [
    "................",
    ".##############.",
    ".#kkkkkkkkkkkk#.",
    ".##############.",
    "..#yyyrryyyyy#..",
    "..#yyrrrryyyy#..",
    "...#yrryyyrr#...",
    "...#yyyyyrrr#...",
    "....#yyyyyr#....",
    "....#yrryyy#....",
    ".....#rryy#.....",
    ".....#yyyy#.....",
    "......#yy#......",
    "......#yy#......",
    ".......##.......",
    "................",
  ],
  cap: [
    "................",
    "................",
    "................",
    ".......##.......",
    ".....##vv##.....",
    "...##vvvvvv##...",
    ".##vvvvvvvvvv##.",
    "...##vvvvvv##.#.",
    "....#vvvvvv#..#.",
    "....#vvvvvv#..y.",
    "....##vvvv##.yyy",
    "......####......",
    "................",
    "................",
    "................",
    "................",
  ],
  tag: [
    "................",
    "................",
    "......######....",
    ".....#yyyyyy#...",
    "....#yy##yyyy#..",
    "...#yyy##yyyyy#.",
    "..#yyyyyyyyyyyy#",
    ".#yyyyyyyyyyyy#.",
    "#yyyyvvvvyyyy#..",
    "#yyyyyyyyyyy#...",
    ".#yyyvvvyyy#....",
    "..#yyyyyyy#.....",
    "...#yyyyy#......",
    "....#yyy#.......",
    ".....###........",
    "................",
  ],
  anvil: [
    "................",
    "..........y.....",
    ".........y.y....",
    "..........y.....",
    "...##########...",
    "####ssssssssss#.",
    ".##sssssssssss#.",
    "...##sssssss##..",
    ".....#sssss#....",
    ".....#sssss#....",
    "....##sssss##...",
    "...#sssssssss#..",
    "...###########..",
    "................",
    "................",
    "................",
  ],
  nib: [
    "................",
    "....########....",
    "....#gggggg#....",
    "....########....",
    "....#vvvvvv#....",
    "....#vv##vv#....",
    "....#vv##vv#....",
    ".....#vv#v#.....",
    ".....#vv#v#.....",
    "......#v#v#.....",
    "......#v##......",
    ".......##.......",
    ".......#........",
    "................",
    "................",
    "................",
  ],
  card: [
    "................",
    "...##########...",
    "...#wwwwwwww#...",
    "...#wvwwwwww#...",
    "...#wwwwwwww#...",
    "...#wwwvvwww#...",
    "...#wwvvvvww#...",
    "...#wvvvvvvw#...",
    "...#wwvvvvww#...",
    "...#wwwvvwww#...",
    "...#wwwwwwww#...",
    "...#wwwwwwvw#...",
    "...#wwwwwwww#...",
    "...##########...",
    "................",
    "................",
  ],
  film: [
    "................",
    "................",
    ".##############.",
    ".#vvvvvvvvvvvv#.",
    ".#vvvvwvvvvvvv#.",
    ".#vvvvwwvvvvvv#.",
    ".#vvvvwwwvvvvv#.",
    ".#vvvvwwwwvvvv#.",
    ".#vvvvwwwvvvvv#.",
    ".#vvvvwwvvvvvv#.",
    ".#vvvvwvvvvvvv#.",
    ".##############.",
    "......####......",
    "....########....",
    "................",
    "................",
  ],
  jos: [
    "................",
    "..############..",
    ".#vvvvvvvvvvvv#.",
    ".#vvvvvvvwwvvv#.",
    ".#vvvvvvvwwvvv#.",
    ".#vvvvvvvvvvvv#.",
    ".#vvvvvvwwwvvv#.",
    ".#vvvvvvvwwvvv#.",
    ".#vvvvvvvwwvvv#.",
    ".#vvvvvvvwwvvv#.",
    ".#vvvvvvvwwvvv#.",
    ".#vvvwwvvwwvvv#.",
    ".#vvvvwwwwvvvv#.",
    ".#vvvvvvvvvvvv#.",
    "..############..",
    "................",
  ],
  face: [
    ".vvvvvvvvvvvvvv.",
    "vvvvhhvhhhvhhvvv",
    "vvvhhhhhhhhhhhvv",
    "vvhhhhhhhhhhhhhv",
    "vhhhhhhhhhhhhhhv",
    "vhhhfhhfhhfhhhhv",
    "vhhffffffffffhhv",
    "vh#####f#####hhv",
    "vh#fhf###fhf#hhv",
    "vhsssssfssssshhv",
    "vhffffffFffffhhv",
    "vvhfffFfffFffhvv",
    "vvvffff###fffvvv",
    "vvttttffftttttvv",
    "vttttttttttttttv",
    ".tttttttttttttt.",
  ],
  lock: [
    "................",
    "................",
    ".....######.....",
    "....##....##....",
    "....#......#....",
    "....#......#....",
    "....#......#....",
    "...##########...",
    "...#kkkkkkkk#...",
    "...#kkk##kkk#...",
    "...#kkk##kkk#...",
    "...#kkkkkkkk#...",
    "...#kkkkkkkk#...",
    "...##########...",
    "................",
    "................",
  ],
  github: [
    "................",
    ".....######.....",
    "...##########...",
    "..###w####w###..",
    ".####ww##ww####.",
    ".####wwwwww####.",
    "####wwwwwwww####",
    "####wwwwwwww####",
    "####wwwwwwww####",
    "####wwwwwwww####",
    ".####wwwwww####.",
    ".#w###wwww#####.",
    "..##w##ww####...",
    "...###ww####....",
    ".....######.....",
    "................",
  ],
  linkedin: [
    "................",
    "..############..",
    ".#bbbbbbbbbbbb#.",
    ".#bwwbbbbbbbbb#.",
    ".#bwwbbbbbbbbb#.",
    ".#bbbbbbbbbbbb#.",
    ".#bwwbwwbwwwbb#.",
    ".#bwwbwwwbbwwb#.",
    ".#bwwbwwbbbwwb#.",
    ".#bwwbwwbbbwwb#.",
    ".#bwwbwwbbbwwb#.",
    ".#bwwbwwbbbwwb#.",
    ".#bbbbbbbbbbbb#.",
    "..############..",
    "................",
    "................",
  ],
  hf: [
    "................",
    ".....######.....",
    "...##yyyyyy##...",
    "..#yyyyyyyyyy#..",
    ".#yyyyyyyyyyyy#.",
    ".#yyy#yyyy#yyy#.",
    "#yyyy#yyyy#yyyy#",
    "#yyyyyyyyyyyyyy#",
    "#yyyyyyyyyyyyyy#",
    "#yy#yyyyyyyy#yy#",
    ".#yy#yyyyyy#yy#.",
    ".#yyy######yyy#.",
    "..#yyyyyyyyyy#..",
    "...##yyyyyy##...",
    ".....######.....",
    "................",
  ],
  chef: [
    "................",
    "................",
    "....###..###....",
    "...#www##www#...",
    "..#wwwwwwwwww#..",
    ".#wwwwwwwwwwww#.",
    ".#wwwwwwwwwwww#.",
    ".#wwwwwwwwwwww#.",
    "..#wwwwwwwwww#..",
    "...#wwwwwwww#...",
    "...##########...",
    "...#vvvvvvvv#...",
    "...#vvvvvvvv#...",
    "...##########...",
    "................",
    "................",
  ],
  radar: [
    "................",
    ".....######.....",
    "...##vvvvvv##...",
    "..#vvvvlvvvvv#..",
    ".#vvvvvlvvvvvv#.",
    ".#vvvvvlvvvyvv#.",
    "#vvvvvvlvvvvvvv#",
    "#llllllllllllll#",
    "#vvvvvvlwvvvvvv#",
    "#vvvvvvlvwvvvvv#",
    ".#vvvvvlvvwvvv#.",
    ".#vvvvvlvvvwvv#.",
    "..#vvvvlvvvvv#..",
    "...##vvvvvv##...",
    ".....######.....",
    "................",
  ],
  bell: [
    "................",
    ".......##.......",
    "......#yy#......",
    "..v..#yyyy#..v..",
    "..v.#yyyyyy#.v..",
    "....#yyyyyy#....",
    "....#yyyyyy#....",
    "...#yyyyyyyy#...",
    "...#yyyyyyyy#...",
    "..#yyyyyyyyyy#..",
    ".##############.",
    "......#kk#......",
    ".......##.......",
    "................",
    "................",
    "................",
  ],
  qblock: [
    "................",
    ".##############.",
    "#ykkkkkkkkkkkky#",
    "#kkkkkkkkkkkkkk#",
    "#kkkkk####kkkkk#",
    "#kkkk##kk##kkkk#",
    "#kkkkkkkk##kkkk#",
    "#kkkkkkk##kkkkk#",
    "#kkkkkk##kkkkkk#",
    "#kkkkkk##kkkkkk#",
    "#kkkkkkkkkkkkkk#",
    "#kkkkkk##kkkkkk#",
    "#kkkkkkkkkkkkkk#",
    "#ykkkkkkkkkkkky#",
    ".##############.",
    "................",
  ],
  stop: [
    "................",
    ".....######.....",
    "....#vvvvvv#....",
    "...#vvvvvvvv#...",
    "..#vvvvwwvvvv#..",
    ".#vvvvvwwvvvvv#.",
    ".#vvvvvwwvvvvv#.",
    ".#vvvvvwwvvvvv#.",
    ".#vvvvvwwvvvvv#.",
    ".#vvvvvvvvvvvv#.",
    "..#vvvvwwvvvv#..",
    "...#vvvvvvvv#...",
    "....#vvvvvv#....",
    ".....######.....",
    "................",
    "................",
  ],
} as const;

export type IconName = keyof typeof BITMAPS;

const FILL: Record<string, string> = {
  "#": "var(--px-ink)",
  w: "var(--px-paper)",
  g: "var(--px-chrome)",
  s: "var(--px-shade)",
  v: "var(--px-violet)",
  l: "var(--px-lav)",
  y: "var(--px-yellow)",
  k: "var(--px-mustard)",
  r: "var(--px-red)",
  h: "var(--px-hair)",
  f: "var(--px-skin)",
  F: "var(--px-skin2)",
  t: "var(--px-tee)",
  b: "var(--px-blue)",
};

/** raw colours for the favicon, which cannot read CSS variables */
export const RAW: Record<string, string> = {
  "#": "#221c45",
  w: "#fdfcf9",
  g: "#e7e3dc",
  s: "#bcb6ab",
  v: "#5a3ff0",
  l: "#cdc6ff",
  y: "#ffe27a",
  k: "#e3b94a",
  r: "#dc4b3a",
  h: "#2b1f1a",
  f: "#f1cbb2",
  F: "#d7a68a",
  t: "#34413b",
  b: "#0a66c2",
};

/** Row-run rects for one bitmap, merged horizontally so each icon is ~40 rects. */
export function iconRects(name: IconName) {
  const rows = BITMAPS[name];
  const out: { x: number; y: number; w: number; fill: string }[] = [];
  rows.forEach((row, y) => {
    if (row.length !== 16) throw new Error(`icon ${name} row ${y} is ${row.length} wide`);
    let x = 0;
    while (x < 16) {
      const c = row[x];
      let w = 1;
      while (x + w < 16 && row[x + w] === c) w++;
      if (c !== ".") out.push({ x, y, w, fill: FILL[c] });
      x += w;
    }
  });
  return out;
}

/** Which drawn icon a project gets when it has no media icon of its own. */
export const PROJECT_ICON: Record<string, IconName> = {
  "bunq-trip-agent": "suitcase",
  "jfam-restaurant-agent": "pizza",
  "vu-ai-hub": "cap",
  "marktplaats-mcp": "tag",
  courseforge: "anvil",
  nib: "nib",
  otterbende: "card",
  cookbuddy: "chef",
  "kamernet-radar": "radar",
  "marktplaats-monitor": "bell",
  "mario-rl": "qblock",
};

/** the same bitmap as a standalone SVG (used to write public/favicon.svg) */
export function iconSvg(name: IconName): string {
  const rects = iconRects(name)
    .map((r) => `<rect x="${r.x}" y="${r.y}" width="${r.w}" height="1" fill="${RAW[BITMAPS[name][r.y][r.x]]}"/>`)
    .join("");
  return `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 16 16" shape-rendering="crispEdges">${rects}</svg>`;
}
